title: CMC QCL HPC Onboarding
description: Research computing onboarding resources and updates.
url: https://www.joanzheng.com
baseurl: /HPC-research-computing-onboarding
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - about.md
  - blog.md

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post